# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190621_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='atendee',
            field=models.ManyToManyField(related_name='trips_joined', to='login.User'),
        ),
    ]
