# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_trip_atendee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='atendee',
            new_name='attendee',
        ),
    ]
