# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190621_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateField(),
        ),
    ]
